project:
  type: website
  output-dir: docs

website:
  navbar:
    logo: "www/fsp_logo_long.png"
    background: "#0085ec"
    left:
      - href: pages/index.qmd
        text: Home
      - pages/about.qmd
      - pages/people.qmd
      - pages/research.qmd
      - pages/courses.qmd
      - pages/blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

