project:
  type: website

website:
  navbar:
    logo: "fsp_logo_long.png"
    background: "#0085ec"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - people.qmd
      - reseach.qmd
      - courses.qmd
      - blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

