project:
  type: website
  output-dir: docs

website:
  favicon: www/fishsize-logo.png
  navbar:
    logo: www/fishsize-logo-wide2.png
    left:
      - href: index.qmd
        text: Home
      - href: pages/team.qmd
        text: Our Team
      - href: pages/research.qmd
        text: Research
      - href: pages/media.qmd
        text: Impact & Outreach
      - href: pages/resources.qmd
        text: Resources
      - href: pages/join.qmd
        text: Join Us!
  page-footer:
    border: false
    background: transparent
    foreground: DimGray

format:
  html:
    logo: "www/fishsize-logo.png"
    theme: Cerulean
    css: styles.css
    toc: false

editor: visual

