project:
  type: website
  output-dir: docs

website:
  favicon: resources/logo-files/fishsize-logo.png
  navbar:
    logo: resources/logo-files/fishsize-logo-wide2.png
    left:
      - href: index.qmd
        text: Home
      - href: pages/team.qmd
        text: Our Team
      - href: pages/research.qmd
        text: Research
      - href: pages/media.qmd
        text: Impact & Outreach
      - href: pages/resources.qmd
        text: Resources
      - href: pages/join.qmd
        text: Join Us!
  page-footer:
    left: |
      Placeholder
    right: |
      Placeholder
    center: |
      ![](resources/logo-files/fishsize-logo-wide.png)
    border: false
    background: primary
    foreground: light

format:
  html:
    logo: resources/logo-files/fishsize-logo.png
    theme: Cerulean
    css: styles.css
    toc: false
    page-layout: full
    grid:
      sidebar-width: 250px
      body-width: 1450px
      margin-width: 100px
      gutter-width: 1.5em

editor: visual

