project:
  type: website
  output-dir: docs

website:
  favicon: "www/fsp_logo_square.png"
  search: false
  navbar:
    brand:
      img: "www/fsp_logo_long.png"
      placement: center
    left:
      - url: index.qmd
        text: About
      - url: pages/people.qmd
        text: Our team
      - href: pages/research.qmd
        text: Research
    right:
      - href: pages/blog.qmd
        text: Media
      - href: pages/software.qmd
        text: Resources
      - href: pages/join.qmd
        text: Join us!

format:
  html:
    theme: slate
    css: styling/styles.css
    toc: true

editor: visual

